apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5xc-service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: f5xc-service-discovery
subjects:
- kind: ServiceAccount
  name: f5xc
  namespace: kube-system
