# Set the namespace for the deplyment at the global level to propagate to the child charts.
namespace: {}

global:
  namespace: "${ namespace }"
  createNamespace: false
  prefix: sentence
  registry: registry.gitlab.com/sentence-app/
  registryTag: latest
  message: "namespace=${ namespace }"
  siteenv: siteenv
  sitename: vk8s-igw-site

adjectives: 
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

animals:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

backgrounds:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

colors:
  enabled: true
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

frontend:
  enabled: false
  registryTag: v3
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

generator:
  enabled: false
  registryTag: v3
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

locations:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP