# Set the namespace for the deplyment at the global level to propagate to the child charts.
namespace: {}

global:
  namespace: "${ namespace }"
  prefix: sentence
  registry: registry.gitlab.com/sentence-app/
  registryTag: dev
  message: "Region:-eu-west-2"
  sitename: arch-aws-eks-site

adjectives: 
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

animals:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

backgrounds:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

colors:
  enabled: true
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

frontend:
  enabled: false
  registryTag: v3
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

generator:
  enabled: false
  registryTag: v3
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP

locations:
  enabled: false
  registryTag: v1
  # set either 'serviceType: NodePort' or 'serviceType: ClusterIP'
  serviceType: ClusterIP