
apiVersion: v1
kind: Service
metadata:
  name: arcadia-stock-transaction
  namespace: arcadiacrypto
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-stock-transaction
